/**
 * app.js – Anaesthetic Billing Checker
 *
 * Deterministic audit checker for Australian MBS anaesthesia billing.
 * Uses official MBS Online data for descriptions and schedule fees.
 * Never fabricates unknown values.
 *
 * Copyright (c) 2026 Bernard McClement
 * Licensed under the MIT License. See LICENSE file in the project root.
 * You may copy, modify, and redistribute this software with attribution.
 */

// ── Rate defaults (editable via UI) ───────────────────────────────
let RVG_BASE_RATE = 106;           // 100% AMA RVG rate per unit
let RVG_GAP_PCT = 60;              // gap percentage applied
let PRIVATE_RATE_PER_UNIT = RVG_BASE_RATE * (RVG_GAP_PCT / 100); // derived
const NOGAP_MIN_PER_UNIT = 35;
const NOGAP_MAX_PER_UNIT = 45;

function recalcPrivateRate() {
  PRIVATE_RATE_PER_UNIT = RVG_BASE_RATE * (RVG_GAP_PCT / 100);
}

// Official MBS data loaded from mbs-data.js (generated by update script)
const MBS_CATALOG = window.MBS_DATA || {};
const MBS_META = window.MBS_DATA_META || {
  source: "not-loaded",
  generatedAt: null,
  totalItems: 0,
};

// ── Code overrides (known anaesthesia items with RVG units) ───────
// These supply RVG units that are NOT in the official MBS XML,
// plus curated short descriptions. Official XML descriptions are
// used as fallback when no override is present.
const CODE_OVERRIDES = {
  17610: { description: "Pre-anaesthesia consultation (initial, <15 mins)", units: 3 },
  17615: { description: "Pre-anaesthesia consultation (15-30 mins)", units: 4 },
  17620: { description: "Pre-anaesthesia consultation (31-45 mins)", units: 6 },
  17625: { description: "Pre-anaesthesia consultation (>45 mins)", units: 8 },
  20560: { description: "Initiation of management of anaesthesia for open heart procedures", units: 20 },
  20914: { description: "Anaesthesia for TURP or similar endoscopic urological procedure", units: 7 },
  22007: { description: "Flexible fibreoptic intubation (difficult airway)" },
  22008: { description: "Double lumen tube / one-lung ventilation" },
  22012: { description: "Blood pressure monitoring via indwelling arterial catheter", units: 3 },
  22014: { description: "Subsequent-day ICU monitoring via indwelling catheter" },
  22015: { description: "Insertion of right heart (Swan-Ganz) balloon catheter", units: 6 },
  22020: { description: "Central vein catheterisation (CVC insertion)", units: 4 },
  22025: { description: "Intra-arterial cannulation (arterial line insertion)", units: 4 },
  22052: { description: "Autologous blood transfusion / cell saver / haemodilution", units: 6 },
  22054: { description: "Intra-operative real-time TOE during cardiac valve surgery", units: 18 },
  23045: { description: "Anaesthesia time unit – 45 minutes", units: 5 },
  23360: { description: "Anaesthesia duration 7h11m–7h20m", units: 40 },
  25000: { description: "Anaesthesia modifier: normal healthy patient (ASA 1)", units: 0 },
  25002: { description: "Anaesthesia modifier: mild systemic disease (ASA 2)", units: 0 },
  25005: { description: "Anaesthesia modifier: severe systemic disease (ASA 4)", units: 2 },
  25008: { description: "Anaesthesia modifier: severe systemic disease (ASA 3)", units: 1 },
  25010: { description: "Anaesthesia modifier: moribund patient (ASA 5)", units: 3 },
  25014: { description: "Anaesthesia modifier: patient aged ≥75 years", units: 1 },
  25020: { description: "Anaesthesia modifier: emergency", units: 4 },
};

// ── Code classification sets ──────────────────────────────────────
const PREOP_CODES = new Set(["17610", "17615", "17620", "17625"]);
const ASA_CODES = new Map([
  ["25000", "ASA 1"], ["25002", "ASA 2"], ["25008", "ASA 3"],
  ["25005", "ASA 4"], ["25010", "ASA 5"],
]);
const INVASIVE_LINE_CODES = new Set(["22015", "22020", "22025"]);
const INVASIVE_MONITOR_CODES = new Set(["22012", "22014"]);
const HIGH_AUDIT_RISK_CODES = new Set(["22014"]);
const CABG_SUPPORT_CODES = new Set(["22051", "22052", "22054", "22015"]);

// ── Procedure fingerprint rules ───────────────────────────────────
const PROCEDURE_RULES = [
  { name: "Standard CABG (core fingerprint)", requiresAll: ["20560", "25005", "22051"] },
  { name: "Cardiac valve replacement/repair case (likely)", requiresAll: ["20560", "22054"] },
  { name: "Emergency re-exploration (baseline)", requiresAll: ["20560", "25020", "22012"] },
];

// ── DOM references ────────────────────────────────────────────────
const codesInput = document.getElementById("codesInput");
const analyzeBtn = document.getElementById("analyzeBtn");
const clearBtn = document.getElementById("clearBtn");
const updateCatalogBtn = document.getElementById("updateCatalogBtn");
const refreshStatusBtn = document.getElementById("refreshStatusBtn");
const catalogStatus = document.getElementById("catalogStatus");
const summaryEl = document.getElementById("summary");
const safetyChecksEl = document.getElementById("safetyChecks");
const warningsEl = document.getElementById("warnings");
const codeBreakdownEl = document.getElementById("codeBreakdown");
const caseVerdictEl = document.getElementById("caseVerdict");
const queryTimerEl = document.getElementById("queryTimer");
const rvgBaseRateInput = document.getElementById("rvgBaseRate");
const rvgGapPctInput = document.getElementById("rvgGapPct");
const rvgPrivateRateDisplay = document.getElementById("rvgPrivateRate");

const IS_HTTP = location.protocol === "http:" || location.protocol === "https:";

// ── RVG rate input handlers ───────────────────────────────────────
function updateRvgDisplay() {
  const computed = RVG_BASE_RATE * (RVG_GAP_PCT / 100);
  if (rvgPrivateRateDisplay) {
    rvgPrivateRateDisplay.textContent = `$${computed.toFixed(2)}`;
  }
}

if (rvgBaseRateInput) {
  rvgBaseRateInput.addEventListener("input", () => {
    const v = parseFloat(rvgBaseRateInput.value);
    if (!isNaN(v) && v >= 0) {
      RVG_BASE_RATE = v;
      recalcPrivateRate();
      updateRvgDisplay();
    }
  });
}

if (rvgGapPctInput) {
  rvgGapPctInput.addEventListener("input", () => {
    const v = parseFloat(rvgGapPctInput.value);
    if (!isNaN(v) && v >= 0 && v <= 100) {
      RVG_GAP_PCT = v;
      recalcPrivateRate();
      updateRvgDisplay();
    }
  });
}

// ── Event listeners ───────────────────────────────────────────────
analyzeBtn.addEventListener("click", () => {
  const t0 = performance.now();
  const parsed = parseCodes(codesInput.value);
  renderAll(parsed);
  const elapsed = (performance.now() - t0).toFixed(1);
  queryTimerEl.classList.remove("hidden");
  queryTimerEl.innerHTML = `<span style="font-size:12px;color:var(--muted)">Analysis completed in ${elapsed} ms</span>`;
});

clearBtn.addEventListener("click", () => {
  codesInput.value = "";
  [summaryEl, safetyChecksEl, warningsEl, codeBreakdownEl, caseVerdictEl, queryTimerEl].forEach((el) => {
    el.classList.add("hidden");
    el.innerHTML = "";
  });
});

// ── Catalog update wiring ─────────────────────────────────────────
if (updateCatalogBtn && refreshStatusBtn && catalogStatus) {
  if (!IS_HTTP) {
    updateCatalogBtn.disabled = true;
    refreshStatusBtn.disabled = true;
    catalogStatus.textContent =
      "Catalog update requires the local server. Run: npm start";
  } else {
    refreshCatalogStatus();

    refreshStatusBtn.addEventListener("click", refreshCatalogStatus);

    updateCatalogBtn.addEventListener("click", async () => {
      updateCatalogBtn.disabled = true;
      catalogStatus.textContent = "Updating from official MBS Online XML…";
      catalogStatus.className = "status-text status-warn";

      try {
        const res = await fetch("/api/update-mbs", { method: "POST" });
        const data = await res.json();
        if (!res.ok || !data.ok) throw new Error(data.error || "Update failed");
        catalogStatus.textContent = "Update complete. Reloading…";
        catalogStatus.className = "status-text status-ok";
        setTimeout(() => location.reload(), 800);
      } catch (err) {
        catalogStatus.textContent = `Update failed: ${err.message}`;
        catalogStatus.className = "status-text status-error";
      } finally {
        updateCatalogBtn.disabled = false;
      }
    });
  }
}

// ── Parse input ───────────────────────────────────────────────────
function parseCodes(raw) {
  const tokens = raw.split(/[\s,;]+/).map((s) => s.trim()).filter(Boolean);
  const valid = tokens.filter((t) => /^\d{5}$/.test(t));
  const counts = {};
  for (const code of valid) counts[code] = (counts[code] || 0) + 1;
  const uniqueCodes = Object.keys(counts).sort();
  return { uniqueCodes, counts, totalEntered: valid.length };
}

// ── Code info lookup (override → catalog → null) ──────────────────
function getCodeInfo(code) {
  const cat = MBS_CATALOG[code] || {};
  const ov = CODE_OVERRIDES[code] || {};

  const description = ov.description || cat.description || null;
  const units = typeof ov.units === "number" ? ov.units : null;
  const scheduleFee =
    typeof ov.scheduleFee === "number"
      ? ov.scheduleFee
      : typeof cat.scheduleFee === "number"
        ? cat.scheduleFee
        : null;

  if (!description && units === null && scheduleFee === null) return null;
  return { description, units, scheduleFee };
}

// ── Procedure detection ───────────────────────────────────────────
function detectProcedures(uniqueCodes) {
  return PROCEDURE_RULES.filter((rule) =>
    rule.requiresAll.every((c) => uniqueCodes.includes(c))
  ).map((r) => r.name);
}

// ── Financial calculations ────────────────────────────────────────
function calculateFinance(uniqueCodes, counts) {
  let knownUnitsTotal = 0;
  let scheduleFeeTotal = 0;
  const unknownCodes = [];

  for (const code of uniqueCodes) {
    const info = getCodeInfo(code);
    const qty = counts[code] || 1;

    if (!info) {
      unknownCodes.push(code);
      continue;
    }

    if (typeof info.units === "number") knownUnitsTotal += info.units * qty;
    if (typeof info.scheduleFee === "number") scheduleFeeTotal += info.scheduleFee * qty;

    if (!info.description && info.units === null && info.scheduleFee === null) {
      unknownCodes.push(code);
    }
  }

  return {
    knownUnitsTotal,
    scheduleFeeTotal,
    unknownCodes,
    noGapMin: knownUnitsTotal * NOGAP_MIN_PER_UNIT,
    noGapMax: knownUnitsTotal * NOGAP_MAX_PER_UNIT,
    privateEstimate: knownUnitsTotal * PRIVATE_RATE_PER_UNIT,
  };
}

// ── Safety checks (traffic light) ─────────────────────────────────
function buildSafetyChecks(uniqueCodes, counts) {
  const preOpCount = countMatching(uniqueCodes, counts, (c) => PREOP_CODES.has(c));
  const procedureCount = countMatching(uniqueCodes, counts, isProcedureCode);
  const timeCount = countMatching(uniqueCodes, counts, isTimeCode);
  const highRiskPresent = uniqueCodes.filter((c) => HIGH_AUDIT_RISK_CODES.has(c));
  const hasInsertion = uniqueCodes.some((c) => INVASIVE_LINE_CODES.has(c));
  const hasMonitoring = uniqueCodes.some((c) => INVASIVE_MONITOR_CODES.has(c));

  const checks = [];

  // 1. Pre-op: exactly one
  checks.push({
    title: "Pre-op assessment code (exactly one expected)",
    status: preOpCount === 1 ? "green" : "red",
    label: preOpCount === 1 ? "PASS" : "HARD FAIL",
    message:
      preOpCount === 1
        ? "Exactly one pre-op assessment code present."
        : preOpCount === 0
          ? "No pre-op assessment code found. Add one (17610/17615/17620/17625) if appropriate."
          : `Multiple pre-op assessment codes detected (${preOpCount}). Usually only one should be billed.`,
  });

  // 2. Procedure present
  checks.push({
    title: "Procedure code present",
    status: procedureCount >= 1 ? "green" : "red",
    label: procedureCount >= 1 ? "PASS" : "HARD FAIL",
    message:
      procedureCount >= 1
        ? `Procedure code(s) detected (count: ${procedureCount}).`
        : "No procedure code detected. Each anaesthetic case should include a procedure code.",
  });

  // 3. Time code: exactly one
  checks.push({
    title: "Time code (exactly one expected)",
    status: timeCount === 1 ? "green" : "red",
    label: timeCount === 1 ? "PASS" : "HARD FAIL",
    message:
      timeCount === 1
        ? "Exactly one time code present."
        : timeCount === 0
          ? "No time code detected (23xxx family). Each case should include one."
          : `Multiple time codes detected (${timeCount}). Usually only one should be present.`,
  });

  // 4. High audit-risk
  checks.push({
    title: "High audit-risk code review",
    status: highRiskPresent.length > 0 ? "amber" : "green",
    label: highRiskPresent.length > 0 ? "QUERY" : "PASS",
    message:
      highRiskPresent.length > 0
        ? `High audit-risk code(s) present: ${highRiskPresent.join(", ")}. Confirm documentation and claiming conditions.`
        : "No configured high audit-risk codes detected.",
  });

  // 5. Line/monitor consistency
  const lmStatus = lineMonitorStatus(hasInsertion, hasMonitoring);
  checks.push({
    title: "Invasive lines vs monitoring consistency",
    status: lmStatus.status,
    label: lmStatus.label,
    message: lmStatus.message,
  });

  // 6. ASA descriptor: exactly one allowed
  const asaPresent = uniqueCodes.filter((c) => ASA_CODES.has(c));
  const asaLabels = asaPresent.map((c) => `${c} (${ASA_CODES.get(c)})`);
  checks.push({
    title: "ASA physical status (exactly one expected)",
    status: asaPresent.length === 1 ? "green" : asaPresent.length === 0 ? "amber" : "red",
    label: asaPresent.length === 1 ? "PASS" : asaPresent.length === 0 ? "QUERY" : "HARD FAIL",
    message:
      asaPresent.length === 1
        ? `Single ASA descriptor present: ${asaLabels[0]}.`
        : asaPresent.length === 0
          ? "No ASA physical status code detected. One of 25000/25002/25005/25008/25010 expected."
          : `Multiple ASA descriptors: ${asaLabels.join(", ")}. Only ONE ASA code per case is valid. High audit risk.`,
  });

  return checks;
}

function lineMonitorStatus(hasInsertion, hasMonitoring) {
  if (hasInsertion && hasMonitoring) {
    return {
      status: "green",
      label: "PASS",
      message: "Invasive line insertion and monitoring codes are both present.",
    };
  }
  if (hasInsertion && !hasMonitoring) {
    return {
      status: "amber",
      label: "QUERY",
      message:
        "Line insertion code present without invasive monitoring code. Query if monitoring should be included.",
    };
  }
  if (!hasInsertion && hasMonitoring) {
    return {
      status: "amber",
      label: "QUERY",
      message:
        "Monitoring code present without line insertion. This can be valid (e.g. lines already in situ from ICU) but should be queried/documented.",
    };
  }
  return {
    status: "green",
    label: "PASS",
    message: "No invasive line/monitoring pair detected. Appropriate for non-invasive cases.",
  };
}

// ── Audit warnings ────────────────────────────────────────────────
function buildWarnings(uniqueCodes, countsOrProcedures, proceduresOrFinance, financeArg) {
  const defaultCounts = Object.fromEntries(uniqueCodes.map((code) => [code, 1]));
  const defaultFinance = { knownUnitsTotal: 0, unknownCodes: [] };

  let counts;
  let procedures;
  let finance;

  if (Array.isArray(countsOrProcedures)) {
    counts = defaultCounts;
    procedures = countsOrProcedures;
    finance = proceduresOrFinance || defaultFinance;
  } else {
    counts = countsOrProcedures || defaultCounts;
    procedures = proceduresOrFinance || [];
    finance = financeArg || defaultFinance;
  }

  const warnings = [];
  const seen = new Set();

  const pushWarning = (severity, text) => {
    const key = `${severity}:${text}`;
    if (seen.has(key)) return;
    seen.add(key);
    warnings.push({ severity, text });
  };

  const hasCode = (code) => uniqueCodes.includes(code);
  const hasAny = (codes) => codes.some((code) => hasCode(code));
  const hasAll = (codes) => codes.every((code) => hasCode(code));

  const has22014 = hasCode("22014");
  const has22012 = hasCode("22012");
  const has20560 = hasCode("20560");
  const has25020 = hasCode("25020");
  const has25005 = hasCode("25005");
  const has22054 = hasCode("22054");
  const has22015 = hasCode("22015");
  const has22052 = hasCode("22052");
  const has23045 = hasCode("23045");
  const has23360 = hasCode("23360");
  const hasCvcInsert = hasCode("22020");
  const hasArtInsert = hasCode("22025");
  const hasInsertion = hasCvcInsert || hasArtInsert;
  const procedureCount = uniqueCodes.filter(isProcedureCode).length;
  const timeCount = countMatching(uniqueCodes, counts, isTimeCode);
  const asaPresent = uniqueCodes.filter((c) => ASA_CODES.has(c));
  const specialtyScope = getSpecialtyScope(uniqueCodes, procedures);
  const cardiacContext = specialtyScope.cardiacContext;

  // ── A) Mutual exclusion / temporal conflict rules ──────────────
  if (has22014 && has22012) {
    pushWarning(
      "hard_fail",
      "22014 (subsequent-day monitoring) appears with 22012 (same-session arterial monitoring). This is a high audit-risk temporal conflict."
    );
  }

  if (has22014 && (hasInsertion || has22015 || has22052 || has22054 || has20560)) {
    pushWarning(
      "hard_fail",
      "22014 is present with intra-operative line/procedure complexity codes. Confirm date-of-service separation and avoid same-day double-dipping."
    );
  }

  if (asaPresent.length > 1) {
    pushWarning(
      "hard_fail",
      `Multiple ASA descriptors detected (${asaPresent.join(", ")}). Only one of 25000/25002/25008/25005/25010 should be billed per case.`
    );
  }

  // ── B) Dependency / orphan rules ──────────────────────────────
  if (timeCount !== 1) {
    pushWarning(
      "soft_warning",
      timeCount === 0
        ? "No anaesthesia time code (23xxx) detected. Most complete claims require exactly one time code."
        : `Multiple time codes detected (${timeCount}). Usually only one time code should be present.`
    );
  }

  if (has22012 && !hasAny(["22025", "22020", "22014"])) {
    pushWarning(
      "context_check",
      "22012 is present without insertion code evidence. This may be valid if lines were already in situ (e.g. ICU transfer), but documentation should be explicit."
    );
  }

  if (hasArtInsert && !has22012) {
    pushWarning(
      "soft_warning",
      "22025 (arterial line insertion) is present without 22012 monitoring. Confirm that ongoing monitoring component is appropriately captured."
    );
  }

  if (hasCvcInsert && !has22012) {
    pushWarning(
      "soft_warning",
      "22020 (CVC insertion) appears without 22012 monitoring. Confirm whether arterial monitoring/line monitoring was omitted or not clinically indicated."
    );
  }

  if (has22015 && !has22012 && cardiacContext) {
    pushWarning(
      "soft_warning",
      "22015 (Swan-Ganz insertion) appears without 22012 monitoring. In high-complexity cardiac cases this combination is unusual and should be reviewed."
    );
  }

  if (has22054 && !has20560) {
    pushWarning(
      "hard_fail",
      "22054 (intra-op TOE for valve surgery) appears without 20560 initiation code. This is a high-risk mismatch for cardiac valve billing context."
    );
  }

  if (has22054 && !has22012 && cardiacContext) {
    pushWarning(
      "soft_warning",
      "22054 is present but 22012 is absent. Confirm invasive monitoring documentation for this cardiac complexity level."
    );
  }

  if (has22052 && !has20560 && cardiacContext) {
    pushWarning(
      "context_check",
      "22052 (cell saver/autologous transfusion) appears without 20560. This can be valid in some major non-cardiac cases; confirm procedural context."
    );
  }

  if (has25020 && !has20560 && cardiacContext) {
    pushWarning(
      "context_check",
      "25020 (emergency modifier) is present without a detected cardiac initiation pattern. Confirm specialty context and modifier appropriateness."
    );
  }

  // ── C) Time / complexity mismatch rules ────────────────────────
  if (has20560 && has23045) {
    pushWarning(
      "hard_fail",
      "20560 appears with 23045 (45-minute time unit). For open-heart complexity this duration is typically inconsistent and requires urgent review."
    );
  }

  if (has22054 && has23045 && cardiacContext) {
    pushWarning(
      "hard_fail",
      "22054 (valve TOE) with 23045 suggests implausibly short duration for valve-level complexity. Check timing and item selection."
    );
  }

  if (has23360 && procedureCount === 0) {
    pushWarning(
      "soft_warning",
      "Long-duration anaesthesia time code (23360) present without any procedure code. Confirm procedure coding completeness."
    );
  }

  // ── D) Cardiothoracic pattern checks ──────────────────────────
  const isCabgCore = cardiacContext && hasAll(["20560", "25005"]);
  if (isCabgCore && !has22012) {
    pushWarning(
      "soft_warning",
      "CABG-like core pattern (20560 + 25005) detected without 22012 monitoring. Confirm arterial monitoring claim and documentation."
    );
  }

  if (isCabgCore && !hasAny(Array.from(CABG_SUPPORT_CODES))) {
    pushWarning(
      "context_check",
      "CABG-like core pattern detected without typical advanced support items (22051/22052/22054/22015). This may be valid but is atypical for standard CABG complexity."
    );
  }

  const isReexplorationPattern = cardiacContext && hasAll(["20560", "25020", "22012"]);
  if (isReexplorationPattern && hasInsertion) {
    pushWarning(
      "soft_warning",
      "Re-exploration pattern (20560 + 25020 + 22012) includes insertion code(s) 22020/22025. If lines were already in situ from ICU, insertion claims may be non-compliant."
    );
  }

  if (has22014 && !has22012 && !hasInsertion) {
    pushWarning(
      "context_check",
      "22014 detected in isolation from same-session line/monitoring items. Ensure this reflects true subsequent-day ICU monitoring context."
    );
  }

  // ── E) Baseline context checks ────────────────────────────────
  if (procedures.length === 0) {
    pushWarning("context_check", "No known procedure fingerprint matched. This may be normal — review manually.");
  }

  if (finance.knownUnitsTotal === 0) {
    pushWarning("context_check", "No known RVG unit codes detected; fee totals are likely underestimates.");
  }

  if (finance.unknownCodes.length > 0) {
    pushWarning(
      "context_check",
      `Codes not fully mapped for units/fees: ${finance.unknownCodes.join(", ")}.`
    );
  }

  return warnings;
}

// ── Render: orchestrator ──────────────────────────────────────────
function renderAll(parsed) {
  const procedures = detectProcedures(parsed.uniqueCodes);
  const finance = calculateFinance(parsed.uniqueCodes, parsed.counts);
  const warnings = buildWarnings(parsed.uniqueCodes, parsed.counts, procedures, finance);
  const safetyChecks = buildSafetyChecks(parsed.uniqueCodes, parsed.counts);

  renderSummary(parsed, procedures, finance);
  renderVerdict(safetyChecks, warnings);
  renderSafetyChecks(safetyChecks);
  renderWarnings(warnings);
  renderCodeBreakdown(parsed.uniqueCodes, parsed.counts);
}

// ── Render: summary ───────────────────────────────────────────────
function renderSummary(parsed, procedures, finance) {
  summaryEl.classList.remove("hidden");
  const specialtyScope = getSpecialtyScope(parsed.uniqueCodes, procedures);

  // Identify procedure codes (20000-21999) and look up their names
  const procedureCodes = parsed.uniqueCodes.filter(isProcedureCode);
  let caseIdHtml = "";
  if (procedureCodes.length > 0) {
    const caseItems = procedureCodes.map((code) => {
      const info = getCodeInfo(code);
      const desc = info && info.description ? info.description : "Unknown procedure";
      return `<div class="case-id-item"><span class="case-id-code">${code}</span> <span class="case-id-desc">${desc}</span></div>`;
    }).join("");
    caseIdHtml = `
    <h3>Case Identification</h3>
    <div class="case-id-box">${caseItems}</div>`;
  } else {
    caseIdHtml = `
    <h3>Case Identification</h3>
    <p class="subtitle">No procedure code (20000–21999) found in input.</p>`;
  }

  const procList = procedures.length
    ? procedures.map((p) => `<li>${p}</li>`).join("")
    : "<li>None confidently matched</li>";

  const catalogTs = MBS_META.generatedAt ? new Date(MBS_META.generatedAt).toLocaleDateString() : "n/a";

  summaryEl.innerHTML = `
    <h2>Summary</h2>
    <p><strong>Codes:</strong> ${parsed.totalEntered} total, ${parsed.uniqueCodes.length} unique</p>
    ${caseIdHtml}

    <h3>Fingerprint Match</h3>
    <ul>${procList}</ul>

    <h3>Specialty Scope</h3>
    <ul class="checklist">
      <li class="${specialtyScope.cardiacContext ? "check-ok" : "check-info"}">
        ${specialtyScope.cardiacContext ? "✅" : "ℹ️"} ${specialtyScope.message}
      </li>
    </ul>

    <h3>Expected for this case</h3>
    <ul class="checklist">${buildExpectedChecks(parsed.uniqueCodes, procedures)}</ul>

    <h3>Estimated Financials</h3>
    <table class="table" style="margin-bottom:4px">
      <tr><td><strong>RVG units</strong></td><td>${finance.knownUnitsTotal}</td><td><strong>Schedule Fee</strong></td><td>${fmt(finance.scheduleFeeTotal)}</td></tr>
      <tr><td><strong>No-gap</strong></td><td>${fmt(finance.noGapMin)} – ${fmt(finance.noGapMax)}</td><td><strong>Private (${RVG_GAP_PCT}%×$${RVG_BASE_RATE})</strong></td><td>${fmt(finance.privateEstimate)}</td></tr>
    </table>
    <p class="subtitle" style="margin:2px 0">Catalog: ${MBS_META.totalItems || 0} items · ${catalogTs} · ${MBS_META.source || "not-loaded"}</p>
  `;
}

// ── Render: overall verdict traffic light ──────────────────────────
function renderVerdict(checks, warnings = []) {
  caseVerdictEl.classList.remove("hidden");

  const hasRed =
    checks.some((c) => c.status === "red") ||
    warnings.some((w) => w.severity === "hard_fail");
  const hasAmber =
    checks.some((c) => c.status === "amber") ||
    warnings.some((w) => w.severity === "soft_warning");

  let overall, label;
  if (hasRed)        { overall = "red";   label = "HARD FAIL — review red items below"; }
  else if (hasAmber) { overall = "amber"; label = "QUERY — review amber items below"; }
  else               { overall = "green"; label = "PASS — all checks green"; }

  const litR = overall === "red"   ? " lit" : "";
  const litA = overall === "amber" ? " lit" : "";
  const litG = overall === "green" ? " lit" : "";
  const vlCls = overall === "red" ? "vl-fail" : overall === "amber" ? "vl-query" : "vl-pass";

  caseVerdictEl.innerHTML = `
    <div class="verdict-bar">
      <div class="tl-housing">
        <div class="tl-light tl-red${litR}"></div>
        <div class="tl-light tl-amber${litA}"></div>
        <div class="tl-light tl-green${litG}"></div>
      </div>
      <span class="verdict-label ${vlCls}">${label}</span>
    </div>
  `;
}

// ── Render: safety checks ─────────────────────────────────────────
function renderSafetyChecks(checks) {
  safetyChecksEl.classList.remove("hidden");

  // Sort by severity: red (HARD FAIL) first, amber (QUERY), green (PASS)
  const rank = { red: 0, amber: 1, green: 2 };
  const sorted = [...checks].sort(
    (a, b) => (rank[a.status] ?? 9) - (rank[b.status] ?? 9)
  );

  const rows = sorted
    .map((ch) => {
      const dotCls =
        ch.status === "green" ? "dot-green" : ch.status === "amber" ? "dot-amber" : "dot-red";
      const labelCls =
        ch.label === "PASS" ? "label-pass" : ch.label === "QUERY" ? "label-query" : "label-fail";
      return `
        <div class="safety-item">
          <span class="traffic-dot ${dotCls}"></span>
          <div>
            <div class="safety-title">${ch.title} <span class="status-label ${labelCls}">${ch.label}</span></div>
            <div>${ch.message}</div>
          </div>
        </div>`;
    })
    .join("");

  safetyChecksEl.innerHTML = `
    <h2>Traffic-Light Safety Checks</h2>
    <div class="safety-list">${rows}</div>
  `;
}

// ── Render: warnings ──────────────────────────────────────────────
function renderWarnings(warnings) {
  warningsEl.classList.remove("hidden");

  if (warnings.length === 0) {
    warningsEl.innerHTML = `<h2>Audit Warnings</h2><p>No warnings.</p>`;
    return;
  }

  const html = warnings
    .map((w) => {
      const cls =
        w.severity === "hard_fail"
          ? "warning-hard"
          : w.severity === "soft_warning"
            ? "warning-soft"
            : "warning-context";
      const pill =
        w.severity === "hard_fail"
          ? "HARD FAIL"
          : w.severity === "soft_warning"
            ? "SOFT WARNING"
            : "CONTEXT CHECK";
      return `<div class="${cls}"><span class="warning-pill">${pill}</span> ${w.text}</div>`;
    })
    .join("");

  warningsEl.innerHTML = `<h2>Audit Warnings</h2>${html}`;
}

// ── Render: code breakdown table ──────────────────────────────────
function renderCodeBreakdown(uniqueCodes, counts) {
  codeBreakdownEl.classList.remove("hidden");

  const rows = uniqueCodes
    .map((code) => {
      const info = getCodeInfo(code);
      const desc = info ? info.description : "Unknown code (not in current data source)";
      const units = info && typeof info.units === "number" ? info.units : "n/a";
      const fee = info && typeof info.scheduleFee === "number" ? info.scheduleFee : null;
      const qty = counts[code] || 1;
      const totalUnits = typeof units === "number" ? units * qty : "n/a";
      const totalFee = fee !== null ? fee * qty : null;

      return `<tr>
        <td>${code}</td>
        <td>${qty}</td>
        <td>${desc}</td>
        <td>${typeof units === "number" ? units : "n/a"}</td>
        <td>${typeof totalUnits === "number" ? totalUnits : "n/a"}</td>
        <td>${fee !== null ? fmt(fee) : "n/a"}</td>
        <td>${totalFee !== null ? fmt(totalFee) : "n/a"}</td>
      </tr>`;
    })
    .join("");

  codeBreakdownEl.innerHTML = `
    <h2>Code Breakdown</h2>
    <div style="overflow-x:auto">
      <table class="table">
        <thead>
          <tr>
            <th>Code</th>
            <th>Qty</th>
            <th>Description</th>
            <th>Units/claim</th>
            <th>Total Units</th>
            <th>Sched Fee/claim</th>
            <th>Total Sched Fee</th>
          </tr>
        </thead>
        <tbody>
          ${rows || '<tr><td colspan="7">No valid 5-digit codes found.</td></tr>'}
        </tbody>
      </table>
    </div>
  `;
}

// ── Expected-for-case checks ──────────────────────────────────────
function buildExpectedChecks(uniqueCodes, procedures) {
  const items = [];

  // Valve case detection
  const isValve = procedures.some((p) => /valve/i.test(p));
  if (isValve) {
    items.push('<li class="check-ok">✅ Valve case detected</li>');
  } else {
    items.push('<li class="check-info">ℹ️ Valve case not detected</li>');
  }

  // Arterial line vs monitoring
  const has22012 = uniqueCodes.includes("22012");
  const has22025 = uniqueCodes.includes("22025");
  if (has22012 && has22025) {
    items.push('<li class="check-ok">✅ Arterial line code present (22025)</li>');
  } else if (has22012 && !has22025) {
    items.push('<li class="check-warn">⚠️ Arterial line code missing (22012 present, 22025 absent)</li>');
  } else {
    items.push('<li class="check-info">ℹ️ No arterial monitoring pattern detected (22012 absent)</li>');
  }

  return items.join("");
}

function getSpecialtyScope(uniqueCodes, procedures) {
  const hasCardiacProcedureFingerprint = procedures.some((p) => /cabg|cardiac|valve|re-exploration/i.test(p));
  const hasCardiacProxyCodes = ["20560", "22054", "22015", "22052"].some((code) => uniqueCodes.includes(code));
  const cardiacContext = hasCardiacProcedureFingerprint || hasCardiacProxyCodes;

  return {
    cardiacContext,
    message: cardiacContext
      ? "Cardiac-context rules active for this case (plus all general anaesthesia checks)."
      : "General anaesthesia checks active; cardiac-specific pattern checks are not applied.",
  };
}

// ── Helpers ───────────────────────────────────────────────────────
function countMatching(uniqueCodes, counts, predicate) {
  let total = 0;
  for (const code of uniqueCodes) {
    if (predicate(code)) total += counts[code] || 0;
  }
  return total;
}

function isProcedureCode(code) {
  const n = Number(code);
  return Number.isFinite(n) && n >= 20000 && n <= 21999;
}

function isTimeCode(code) {
  return /^23\d{3}$/.test(code);
}

function fmt(value) {
  return new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" }).format(value);
}

// ── Catalog status ────────────────────────────────────────────────
async function refreshCatalogStatus() {
  if (!IS_HTTP || !catalogStatus) return;

  catalogStatus.className = "status-text status-warn";
  catalogStatus.textContent = "Checking catalog status…";

  try {
    const res = await fetch("/api/meta");
    const data = await res.json();
    if (!res.ok || !data.ok) throw new Error(data.error || "Status check failed");

    const meta = data.meta || {};
    const ts = meta.generatedAt ? new Date(meta.generatedAt).toLocaleString() : "unknown";
    catalogStatus.className = "status-text status-ok";
    catalogStatus.textContent = `Catalog: ${meta.totalItems || 0} items | Generated: ${ts} | Source: ${meta.source || "unknown"}`;
  } catch (err) {
    catalogStatus.className = "status-text status-error";
    catalogStatus.textContent = `Status check failed: ${err.message}`;
  }
}
